# Generated by Django 3.2.9 on 2021-12-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
