# Generated by Django 3.2.9 on 2021-12-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created',
            new_name='created_at',
        ),
    ]
